// Self-contained demo of a self-hosted environment worker.
//
// Creates an agent with agent_toolset_20260401 plus a custom current_time tool,
// opens a session against ANTHROPIC_ENVIRONMENT_ID, sends a prompt, then runs an
// EnvironmentWorker (poll for work, set up the workdir + skills, run the local
// tools against the session's agent.tool_use and agent.custom_tool_use events
// while heartbeating the work-item lease, force-stop on exit, loop) until a
// deadline fires.
//
// Required environment variables:
//
//	ANTHROPIC_API_KEY         - your API key (read by the SDK client)
//	ANTHROPIC_ENVIRONMENT_ID  - a self-hosted environment to poll
//	ANTHROPIC_ENVIRONMENT_KEY - the environment's key (authorizes both the
//	                            work-poll calls and the per-session calls)
//
// Security model: the worker executes bash and file operations directly on the
// host. Run inside a container or other isolation boundary you control.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/anthropics/anthropic-sdk-go"
	"github.com/anthropics/anthropic-sdk-go/lib/environments"
	"github.com/anthropics/anthropic-sdk-go/packages/param"
	"github.com/anthropics/anthropic-sdk-go/tools/agenttoolset"
)

// currentTimeTool is a custom anthropic.BetaTool that returns the local time.
// It demonstrates extending the default tool list alongside
// agent_toolset_20260401.
type currentTimeTool struct{}

func (currentTimeTool) Name() string        { return "current_time" }
func (currentTimeTool) Description() string { return "Get the current local time on the worker host." }
func (currentTimeTool) InputSchema() anthropic.BetaToolInputSchemaParam {
	return anthropic.BetaToolInputSchemaParam{Properties: map[string]any{}}
}
func (currentTimeTool) Execute(context.Context, json.RawMessage) ([]anthropic.BetaToolResultBlockParamContentUnion, error) {
	return []anthropic.BetaToolResultBlockParamContentUnion{
		{OfText: &anthropic.BetaTextBlockParam{Text: time.Now().Format(time.RFC3339)}},
	}, nil
}

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))
	client := anthropic.NewClient()
	ctx := context.Background()

	envID := mustEnv("ANTHROPIC_ENVIRONMENT_ID")
	environmentKey := mustEnv("ANTHROPIC_ENVIRONMENT_KEY")

	agent, err := client.Beta.Agents.New(ctx, anthropic.BetaAgentNewParams{
		Name:   "self-hosted-runner-example",
		Model:  anthropic.BetaManagedAgentsModelConfigParams{ID: "claude-haiku-4-5"},
		System: param.NewOpt("You are running in a self-hosted sandbox. Use the available tools to answer."),
		Tools: []anthropic.BetaAgentNewParamsToolUnion{
			{OfAgentToolset20260401: &anthropic.BetaManagedAgentsAgentToolset20260401Params{
				Type: "agent_toolset_20260401",
			}},
			{OfCustom: &anthropic.BetaManagedAgentsCustomToolParams{
				Type:        "custom",
				Name:        "current_time",
				Description: "Get the current local time on the worker host.",
				InputSchema: anthropic.BetaManagedAgentsCustomToolInputSchemaParam{
					Type:       "object",
					Properties: map[string]any{},
				},
			}},
		},
	})
	if err != nil {
		fatal(logger, "create agent", err)
	}
	logger.Info("created agent", slog.String("agent_id", agent.ID))
	defer func() {
		// Run cleanup with a fresh-but-deadlined context so a cancelled
		// parent ctx doesn't skip Archive.
		cleanup, cancel := context.WithTimeout(context.WithoutCancel(ctx), 10*time.Second)
		defer cancel()
		if _, err := client.Beta.Agents.Archive(cleanup, agent.ID, anthropic.BetaAgentArchiveParams{}); err != nil {
			logger.Warn("archive agent failed", slog.Any("error", err))
		}
	}()

	session, err := client.Beta.Sessions.New(ctx, anthropic.BetaSessionNewParams{
		Agent:         anthropic.BetaSessionNewParamsAgentUnion{OfString: param.NewOpt(agent.ID)},
		EnvironmentID: envID,
		Title:         param.NewOpt("self-hosted-runner-example"),
	})
	if err != nil {
		fatal(logger, "create session", err)
	}
	logger.Info("created session", slog.String("session_id", session.ID))
	defer func() {
		cleanup, cancel := context.WithTimeout(context.WithoutCancel(ctx), 10*time.Second)
		defer cancel()
		if _, err := client.Beta.Sessions.Delete(cleanup, session.ID, anthropic.BetaSessionDeleteParams{}); err != nil {
			logger.Warn("delete session failed", slog.Any("error", err))
		}
	}()

	// TODO(codegen): the autogenerated
	// BetaManagedAgentsEventParamsOfUserMessage helper omits the
	// required `type` field — compare its body (no type_ arg) with
	// sibling helpers like BetaManagedAgentsEventParamsOfUserInterrupt
	// (which do take type_). Server validators reject the payload with
	// "events[0].type: Field required". Workaround: construct the
	// union directly with Type set. Remove the workaround once the
	// generator emits the type assignment in the helper.
	_, err = client.Beta.Sessions.Events.Send(ctx, session.ID, anthropic.BetaSessionEventSendParams{
		Events: []anthropic.BetaManagedAgentsEventParamsUnion{
			{OfUserMessage: &anthropic.BetaManagedAgentsUserMessageEventParams{
				Type: anthropic.BetaManagedAgentsUserMessageEventParamsTypeUserMessage,
				Content: []anthropic.BetaManagedAgentsUserMessageEventParamsContentUnion{
					{OfText: &anthropic.BetaManagedAgentsTextBlockParam{
						Type: anthropic.BetaManagedAgentsTextBlockTypeText,
						Text: "What is the current time? Also run pwd to show me the working directory.",
					}},
				},
			}},
		},
	})
	if err != nil {
		fatal(logger, "send user message", err)
	}

	// Run the worker until the deadline fires.
	workCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	worker := environments.NewEnvironmentWorker(client, environments.EnvironmentWorkerOptions{
		EnvironmentID:  envID,
		EnvironmentKey: environmentKey,
		Workdir:        ".",
		Logger:         logger,
		// Per-session tool factory: the standard agent_toolset_20260401 set
		// (bound to the session's workdir) plus a custom current_time tool.
		ToolsFunc: func(env *agenttoolset.AgentToolContext) []anthropic.BetaTool {
			return append(agenttoolset.BetaAgentToolset20260401(env), currentTimeTool{})
		},
	})
	// worker.Run polls for work and loops. If you instead already hold a
	// claimed work item — e.g. inside an `ant worker poll --on-work` hook,
	// which exports ANTHROPIC_WORK_ID / ANTHROPIC_ENVIRONMENT_ID /
	// ANTHROPIC_SESSION_ID / ANTHROPIC_ENVIRONMENT_KEY — service that single
	// item with worker.HandleItem(ctx, environments.HandleItemOptions{}).
	if err := worker.Run(workCtx); err != nil {
		fatal(logger, "worker", err)
	}

	// Print a compact transcript.
	fmt.Println("\n--- session transcript ---")
	pager := client.Beta.Sessions.Events.ListAutoPaging(ctx, session.ID, anthropic.BetaSessionEventListParams{
		Limit: param.NewOpt(int64(100)),
	})
	for pager.Next() {
		ev := pager.Current()
		fmt.Printf("%-28s %s\n", ev.Type, summariseEvent(ev))
	}
	if err := pager.Err(); err != nil {
		fatal(logger, "list events", err)
	}
}

func summariseEvent(ev anthropic.BetaManagedAgentsSessionEventUnion) string {
	switch ev.Type {
	case "agent.tool_use", "agent.custom_tool_use":
		in, _ := json.Marshal(ev.Input)
		return fmt.Sprintf("%s %s", ev.Name, truncate(string(in), 80))
	case "user.tool_result", "user.custom_tool_result", "agent.message", "user.message":
		return truncate(ev.RawJSON(), 120)
	default:
		return ev.ID
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

func mustEnv(k string) string {
	v := os.Getenv(k)
	if v == "" {
		fmt.Fprintf(os.Stderr, "missing required env var %s\n", k)
		os.Exit(1)
	}
	return v
}

func fatal(l *slog.Logger, op string, err error) {
	l.Error(op+" failed", slog.Any("error", err))
	os.Exit(1)
}
