#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running Go build"
go build .

# Compile the tests but don't run them
go test -c .

echo "==> Building examples"
cd examples && go build ./...